### PR TITLE
misc requirements

### PR DESCRIPTION
**Pull request by patrickkwang**
Query: query_message
Result: node_bindings and edge_bindings
QNode: node_id
QEdge: edge_id

### CODE REVIEW

**Comment by patrickkwang** [comment]
#29

**Comment by edeutsch** [comment]
For us, a query_message{} is not required if a previous_message_processing_plan{} is provided.

**Comment by edeutsch** [comment]
also, for us, not 100% of Results will have node_bindings and edge_bindings.

I do not think that enforcing this minimal set of requirements will benefit us. Most of our query results will conform to this, but I know that we do currently and will have some results that cannot conform to these requirements.

Is it better that we set very restrictive requirements knowing that some reasoners won't always conform to these requirements?

Or is it better to leave these things somewhat unconstrained?

I can go ahead and approve this if you like and we can merge it, but RTX will sometimes violate it.

**Comment by patrickkwang** [comment]
The purpose of this standard is to promote/ensure interoperability. The bindings format is critical for allowing us to evaluate, compare, and build upon reasoner results. There will of course be services that cannot conform to the standard and therefore won't be used by whatever uber-reasoner aggregates or pipelines these services. But it sounds like you have a single endpoint that only sometimes conforms to the this format? Is there a chance this can be split into multiple endpoints, one of which is fully compliant with the proposed spec?

**Comment by vdancik** [comment]
For us `qg_id` is always identical to `kg_id`. I think node_binding and edge_binding should be optional for cases when `qg_id != kg_id`. The remaining three requirements (query_message, node_id, edge_id) are not problematic for us.

**Comment by edeutsch** [comment]
I think this PR is obsolete. At minimum, the attribute names have changed by now. Can we expunge this PR?

**Comment by patrickkwang** [comment]
This branch is once again fully ahead of master.

**Pull request merged**
