### PR TITLE
Add recommendation to use biolink-model for entity type

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by patrickkwang** [comment]
Good idea. Should we add an `externalDocs` for these pointing to some official resource for the biolink model?
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-20

**Comment by patrickkwang** [comment]
If we make `BiolinkNode` and `BiolinkEdge` components, these could contain the external documentation links and reduce some redundancy.

**Comment by patrickkwang** [comment]
The way I read this, it seems like we want a [related_to](https://biolink.github.io/biolink-model/docs/related_to.html) rather than an [edge_label](https://biolink.github.io/biolink-model/docs/edge_label.html).

**Comment by edeutsch** [comment]
I confess that I do not understand these last two comments.

**Comment by patrickkwang** [comment]
@cmungall: Do you follow? Do you agree? Would you like to make the edits?

**Comment by patrickkwang** [comment]
@cmungall I can't seem to add you as a reviewer, but please let us know if this looks reasonable.

**Pull request merged**
