### PR TITLE
add a mechanism to provide logging information

### PR DESCRIPTION
**Pull request by edeutsch**
I am trying to propose this to the `experimental` branch.

### CODE REVIEW

**Comment by webyrd** [comment]
I'm trying to understand the intent of this logging information.  Is the purpose to be able to diagnose a mis-configured web server or ARA or KP?  As opposed to tracking the reasoning involved, or data provenance, for example?  Or is the intent to capture and report semantic or reasoning information, in addition to standard server-related errors?

**Comment by vdancik** [comment]
Logging sounds reasonable for development branch only

**Comment by edeutsch** [comment]
FYI, here is an example of how we are using log currently:
https://arax.rtx.ai/beta/?m=2650
- Click on [Messages] on the left to see a view of the logging that is returned.
- if you want to see the JSON, click on [Dev Info] and browser-search for `"log":` including the double quotes
I'm not currently proposing a specific structure within `log`, but just that there could be one and that's how we're doing it.

**Comment by edeutsch** [comment]
In response to @webyrd questions:
>I'm trying to understand the intent of this logging information. Is the purpose to be able to diagnose a mis-configured web server or ARA or KP? 

Probably not the web server, but the ARA or KP yes. More likely the ARA than a KP.

>As opposed to tracking the reasoning involved, or data provenance, for example? Or is the intent to capture and report semantic or reasoning information, in addition to standard server-related errors?

It is intended to convey any sort of free text information about the process of reasoning or answering the query that a user might like to know. (or in the case of WARNINGS or ERRORs) probably needs to know. In the above example, there is a warning because a set of proteins was provided but is_set was set to false. User intent was clear, so instead of erroring out, we just issue a warning. Also in the set of proteins, one is not recognized. Again, we could error out, but we decided to just issue a WARNING and proceed with the rest of the list. The user can then decide whether to be content with what was done or issue an adjusted query. And then there's lots of INFO information. Probably too much. It gives some insight into what is going on behind the curtain. At the moment, we like it for testing and debugging, but see its value for consumers.

**Comment by edeutsch** [comment]
Maybe this will be expanded in the future, but for now, let's get this into `extended` as a top-level container as is.

**Pull request merged**
