### PR TITLE
Added "translator" and "reasoner" tags

### PR DESCRIPTION
**Pull request by newgene**
Adding "translator" and "reasoner" tags in this template to indicate an API as a "Translator's KP API implemented as ReasonerStdAPI", when [registered in SmartAPI registry](https://smart-api.info/add_api).

"translator" tag is included for all Translator KP APIs, and "reasoner" tag is specific for Reasoner APIs.

### CODE REVIEW

**Comment by ehinderer** [comment]
Is the "reasoner" name outdated? I thought that "reasoner" was the old name for what we're calling an ARA now.

**Comment by newgene** [comment]
@edeutsch @ehinderer it does not have to be called "reasoner", can be other name after the rebranding. But I think it's necessary to add a tag to indicate the implement type of the KP APIs, "reasoner" KP API is one of them.

**Comment by patrickkwang** [comment]
@newgene Should these tags be associated with specific operations? My reading of the OpenAPI Specification is that this top-level tag list is meant just to provide metadata around the tags used by specific operations. Listing the reasoner tag as you've done should not be taken to imply that every endpoint described by the OpenAPI schema is a Reasoner API endpoint, as these services may provide arbitrary additional operations. Requiring the reasoner tag on the /query endpoint seems sensible, though.

**Comment by vdancik** [comment]
We can call it Knowledge-Exchange API (KEXAPI)

**Comment by webyrd** [comment]
> We can call it Knowledge-Exchange API (KEXAPI)

Not bad!  :)

**Comment by edeutsch** [comment]
Sentiment seems to be strongly in favor of approval with a proviso that we may alter it again later based on the decisions of the renaming. I'll hold it open until Monday and then merge unless there is opposition.

**Pull request merged**
